# Generated by Django 5.2.9 on 2025-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0004_rtsptable_stream_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelenabled',
            name='fire_detection_confidence',
            field=models.FloatField(default=0.5, help_text='Confidence threshold for fire detection (0.0-1.0)'),
        ),
    ]
